#!/usr/bin/env perl
#
# Copyright (C) 2004-2006 by Socialtext, Inc.
#

use strict;
use warnings;

use File::Basename qw(dirname);

my $dir = dirname($0);

system( "$dir/diffs-since $ARGV[0] | vim-pager" );
