#!/usr/bin/env perl
#
# Copyright (C) 2004-2006 by Socialtext, Inc.
#

use strict;
use warnings;

use File::Path qw(rmtree);
use Getopt::Long;
use Readonly;

Readonly my $SVN_REPO => 'https://repo.socialtext.net:8999';

my %opts;
GetOptions(
    'type:s'    => \$opts{type},
    'source:s'  => \$opts{source},
    'message:s' => \$opts{message},
    'version:s' => \$opts{version},
    'help'      => \$opts{help},
) or exit 1;

die "not yet implemented ...";
