#!/usr/bin/env perl
#
# Copyright (C) 2004-2006 by Socialtext, Inc.
#
use strict;
use warnings;
use Linux::MemInfo;
my %mem = get_mem_info;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Spiffy ':XXX';
XXX \%mem;
